scr/views/view_highchart.py
from flask import Blueprint, render_template, request, jsonify
from scr.models.model_highchart import model_highchart

main = Blueprint('highchart_bp', __name__)


@main.route('/highchart')
def maintenance():
    # Datos para el gráfico
    data = [5, 10, 15, 20, 25]

    # Renderizar la plantilla HTML con los datos
    return render_template('ejemplo1.html', data=data)


@main.route('/velocimetro')
def spedometer():
    # Renderizar la plantilla HTML con los datos
    result = model_highchart.get_ejemplo2()
    # Procesar los datos para la plantilla
    data = {
        'meses': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        'canales': {}
    }
    for row in result:
        mes = row.mes - 1  # Restar 1 para ajustar al índice de la lista
        canal = row.canal_de_venta
        monto = float(row.monto)  # Convertir Decimal a float
        if canal not in data['canales']:
            print([0] * 12)
            data['canales'][canal] = [0] * 12
        data['canales'][canal][mes] += monto
    print(data)
    return render_template('ejemplo2.html', data=data)


@main.route('/ejemplo4')
def sample4():
    result = model_highchart.get_ejemplo4()

    data = {
        'meses': model_highchart.get_month_names(),
        'montos': [0] * 12  # Inicializa con 12 ceros
    }
    for row in result:
        mes = row.mes  # Month is already in 1-12 range
        if 1 <= mes <= 12:  # Ensure the month is within the valid range
            monto = float(row.monto)  # Convertir Decimal a float
            data['montos'][mes - 1] += monto  # Adjust index to be 0-11 for list

    print(data)

    # Renderizar la plantilla HTML con los datos
    return render_template('ejemplo4.html', data=data)


@main.route('/ejemplo3')
def sample3():
    result = model_highchart.get_ejemplo3()
    # Procesar los datos para la plantilla
    data = {}
    for row in result:
        zona = row.zona_cobranza
        forma_pago = row.forma_de_pago
        monto = row.monto_cobrado

        if zona not in data:
            data[zona] = {}
        data[zona][forma_pago] = monto

        # Convertir los datos a un formato adecuado para Highcharts
    categories = list(data.keys())
    series_data = []
    formas_pago = list(set(fp for zona in data.values() for fp in zona.keys()))

    for forma_pago in formas_pago:
        data_for_forma_pago = [data[zona].get(forma_pago, 0) for zona in categories]
        series_data.append({
            'name': forma_pago,
            'data': data_for_forma_pago
        })
    print(series_data)
    # Renderizar la plantilla HTML con los datos
    return render_template('ejemplo3.html', categories=categories, series_data=series_data)


# Función para obtener los datos de las medallas
def obtener_datos_medallas():
    result = model_highchart.get_ejemplo5()
    datas = {
        'paises': [],
        'oro': [],
        'plata': [],
        'bronce': [],
    }

    for row in result:
        datas['paises'].append(row.country)
        datas['oro'].append(row.gold)
        datas ['plata'].append(row.silver)
        datas['bronce'].append(row.bronze)

    # https://en.wikipedia.org/wiki/2024_Summer_Olympics_medal_table
    return datas


@main.route('/ejemplo5')
def sample5():
    datos = obtener_datos_medallas()
    # Renderizar la plantilla HTML con los datos
    print(datos)
    return render_template('ejemplo5.html', datos=datos)


@main.route('/ejemplo6')
def sample6():

    #model_highchart.obtenergeojson()

    # Renderizar la plantilla HTML con los datos
    return render_template('ejemplo6.html')


@main.route('/ejemplo6map', methods=['GET', 'POST'])
def sample6map():
    if request.method == "POST":
        data = request.get_json()
        print(data)
        pais = data.get('paises', None)
        result = model_highchart.get_ejemplo6(pais)
        print(result)
        datas = []
        for row in result:
            datas.append([row['hckey'], row['venta'], row['ciudad']])

        return jsonify(datas)

scr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %}</title>

        <!---Agrega un favico , es agregar una pequeña imagen localizada en el tab de un navegador --->
    <link  rel="icon" type="image/x-icon" href="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1f47d.svg" />
    <!-- Enlace a Bootstrap 5.0.2 CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>

</head>
<body>

<header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">HIGHCHART</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('highchart_bp.maintenance') }}">Ejemplo 1</a>
        </li>

        <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('highchart_bp.spedometer') }}">Ejemplo 2</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('highchart_bp.sample3') }}">Ejemplo 3</a>
        </li>

         <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('highchart_bp.sample4') }}">Ejemplo 4</a>
        </li>

         <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('highchart_bp.sample5') }}">Ejemplo 5</a>
        </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('highchart_bp.sample6') }}">Ejemplo 6</a>
        </li>

      </ul>

      <span class="navbar-text"> HIGHCHART </span>
    </div>
  </div>
</nav>

</header>

    <div class="container py-3">
        {% block body %}
        {% endblock %}
    </div>

<!-- Bootstrap 5.0.2 incluye la biblioteca Popper, por lo que no necesitas cargarla por separado. -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<!--- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>-->

        <!--- highcharts-->
<!--- Lib. para mapas-->
    <script src="https://code.highcharts.com/maps/highmaps.js"></script>

<!---
Estás incluyendo tanto highmaps.js como highcharts.js. Si solo necesitas mapas, puedes eliminar highcharts.js ya
 que highmaps.js también incluye las funcionalidades básicas de
 -->
   <!---  <script src="https://code.highcharts.com/highcharts.js"></script>-->
    <script src="https://code.highcharts.com/highcharts-more.js"></script>

    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/annotations.js"></script>
    <script src="https://code.highcharts.com/modules/boost.js"></script>
    <script src="https://code.highcharts.com/modules/pattern-fill.js"></script>
    <script src="https://code.highcharts.com/modules/xrange.js"></script>
    <script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
    <script src="https://code.highcharts.com/modules/variable-pie.js"></script>

</body>
</html>

scr/templates/ejemplo1.html
 {% extends './base.html' %}

 {%  block title %}Ejemplo 1 {% endblock %}

 {% block body %}

 <div id="container" style="min-width: 310px; height: 400px; margin:0 auto"></div>

 <script type="text/javascript">

  document.addEventListener('DOMContentLoaded',function(){
   Highcharts.chart('container',{
      chart:{
       type: 'bar'
      },

      title:{
       text:'Ejemplo de Gráfico de Highchart'
      },
      xAxis:{
       categories:['A','B','C','D','E']
      },
      yAxis:{
       title:{
         text: 'Valores'
       }
      },
      series: [{
       name:'Datos',
       data: {{ data | tojson }}
       }]
    });
  });

 </script>
 {% endblock %}

scr/templates/ejemplo2.html
 {% extends './base.html' %}

 {%  block title %}Ejemplo 2 {% endblock %}

 {% block body %}

 <div id="container" style="min-width: 310px; height: 400px; margin:0 auto"></div>

 <script type="text/javascript">

  document.addEventListener('DOMContentLoaded',function(){
    var data ={{ data | tojson}};

    var seriesData = Object.keys(data.canales).map(function(canal){
      return {
        name: canal,
        data: data.canales[canal]
      };
    });

    Highcharts.chart('container',{

     chart:{
       type: 'line'
     },
     title:{
       text:'Ventas Mensuales'
     },

     subtitle:{
       text: '2023-2024'
     },

     xAxis:{
       categories:data.meses
     },
     yAxis:{
       title:{
         text: 'Monto Acumulado'
       }
     },
     plotOptions:{
       line:{
         dataLabels:{
          enabled:true
         },
         enableMouseTracking: false
       }
     },
      series : seriesData
    });

  });

 </script>
 {% endblock %}

scr/templates/ejemplo3.html
{% extends './base.html' %}

{% block title %} Ejemplo 3 {% endblock %}
{% block body %}

    <div id="container" style="width: 600px; height:400px; margin:0 auto"></div>

<script type="text/javascript">
      document.addEventListener('DOMContentLoaded',function(){
        //variables de entorno
        var categories ={{ categories | tojson }}
        var seriesdata ={{ series_data | tojson }}
        //configuración del gráficode barras

        Highcharts.chart('container',{
        chart:{
                type: 'column'
              },
           //titulo del grafico
           title:{
                text :'Datos de Cobranza'
           },
           subtitle:{
            text: 'por Zonas'
            },
          //config. eje X
          xAxis:{
            categories : categories,
            crosshair: true,
            accessibility :{
                description:'Zona de Cobranza'
                }
             },
             //Config eje Y
          yAxis:{
                min:0,
                title: {
                        text: 'Monto Cobrado'
                        }
                },
            //tooltip
           tooltip:{
                valueSuffix : ' ($)'
                },

           //opciones del Plot

           plotOptions:{
                    column:{
                        pointPadding :0.2,
                        borderWidth: 0
                        }
             },
             //Serie de Datos
             series: seriesdata
          });
    });

</script>
 {% endblock %}

scr/templates/ejemplo4.html
{% extends './base.html' %}

{% block title  %}Ejemplo4 {% endblock %}
{% block body %}

    <figure class ="highcharts-figure">
        <div id ="container"></div>
        <p class="higcharts-description">
               Gráfico con 3 botones que puedes facilmente cambiar el tipo de gráfico.
        </p>

        <button id="plain">Plain</button>
        <button id="inverted">Inverted</button>
        <button id="polar">Polar</button>
    </figure>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function(){
            var data = {{ data | tojson}};
           const chart = Highcharts.chart('container',{
                   title:{
                           text: 'Venta  por Mes',
                           align : 'left'
                    },
                   subtitle:{
                            text: 'Año de Ventas: 2024'+
                            '<a href="https://www.youtube.com"' +
                            'target="_blank">youtube</a>',
                            align:'left'
                            },
                    colors:[
                        '#4caefe', '#3fbdf3', '#35c3e8', '#2bc9dc', '#20cfe1',
                            '#16d4e6', '#0dd9db', '#03dfd0', '#00e4c5', '#00e9ba',
                            '#00eeaf', '#23e274'
                        ],
                    //config eje X
                    xAxis:{
                        categories: data.meses
                    },

                    series:[{
                        type: 'column',
                        name: 'Montos',
                        borderRadius:5,
                        colorByPoint:true,
                        data: data.montos,
                        showInLegend:false
                    }]
            });
            //boton Plain
            document.getElementById('plain').addEventListener('click',()=>{
                chart.update({
                    chart:{
                        inverted:false,
                        polar:false,
                        type:'column'
                        },
                    subtitle:{
                                text: 'Año de Ventas: 2024'+
                                '<a href="https://www.youtube.com"' +
                                'target="_blank">youtube</a>',
                                align:'left'
                                }
                });
            });

            //boton polar
            document.getElementById('polar').addEventListener('click',()=>{
                chart.update({
                    chart:{
                        inverted:false,
                        polar:true,
                         type:'column'

                        },
                    subtitle:{
                                text: 'Año de Ventas: 2024'+
                                '<a href="https://www.youtube.com"' +
                                'target="_blank">youtube</a>',
                                align:'left'
                                }
                });
            });

          //boton inverted
            document.getElementById('inverted').addEventListener('click',()=>{
                chart.update({
                    chart:{
                        inverted:true,
                        polar:false,
                         type:'column'
                        },
                    subtitle:{
                                text: 'Año de Ventas: 2024'+
                                '<a href="https://www.youtube.com"' +
                                'target="_blank">youtube</a>',
                                align:'left'
                                }
                });
            });


        });

    </script>
{% endblock %}

scr/templates/ejemplo5.html
{% extends './base.html' %}
{% block title %}Ejemplo 5{% endblock %}
{% block body %}

<div id="container" style="width: 600px; height: 400px; margin: 0 auto"></div>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
     var datos = {{ datos | tojson }};
        Highcharts.chart('container', {
            colors: ['#FFD700', '#C0C0C0', '#CD7F32'],
            chart: {
                type: 'column',
                inverted: true,
                polar: true
            },
            title: {
                text: 'Medallas de los Juegos Olímpicos Francia 2024 (TOP 5)',
                align: 'left'
            },
            tooltip: {
                outside: true
            },
            pane: {
                size: '85%',
                innerSize: '20%',
                endAngle: 270
            },
            xAxis: {
                tickInterval: 1,
                labels: {
                    align: 'right',
                    useHTML: true,
                    allowOverlap: true,
                    step: 1,
                    y: 3,
                    style: {
                        fontSize: '13px'
                    }
                },
                lineWidth: 0,
                gridLineWidth: 0,
                categories: datos.paises
            },
            yAxis: {
                lineWidth: 0,
                tickInterval: 25,
                reversedStacks: false,
                endOnTick: true,
                showLastLabel: true,
                gridLineWidth: 0
            },
            plotOptions: {
                column: {
                    stacking: 'normal',
                    borderWidth: 0,
                    pointPadding: 0,
                    groupPadding: 0.15,
                    borderRadius: '50%'
                }
            },
            series: [{
                name: 'Medallas de Oro',
                data: datos.oro
            }, {
                name: 'Medallas de Plata',
                data: datos.plata
            }, {
                name: 'Medallas de Bronce',
                data: datos.bronce
            }]
        });
    });
</script>

{% endblock %}

scr/templates/ejemplo6.html
{% extends './base.html' %}

{% block title %}  Ejemplo 6 {% endblock %}

{%  block body %}
    <script src="{{ url_for('static', filename='js/util_highchart.js') }}"></script>
     <div class="row">
            <div class="col-sm-12">
                <div id="container" style="height: 700px;  min-width: 510px; max-width: 800px;  margin: 0 auto;" ></div>
            </div>
     </div>

    <!--- para ejemplo 6 --->
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {

       var varGeoData='https://code.highcharts.com/mapdata/countries/mx/mx-all.geo.json';

        var formData = {
            paises: 1
        };

        Ajax_HighChart(formData, '/ejemplo6map').then(function(response) {
            // Aquí actualizas el mapa y los datos
            LoadMap(varGeoData, response);
        })
        .catch(function(error) {
            alert('Error al cargar datos: ' + error);
        });

    function LoadMap(geoLink, data) {
        (async () => {

            const topology = await fetch(geoLink).then(response => response.json());

            Highcharts.mapChart('container', {
                chart: {
                    map: topology
                },
                title: {
                    text: 'Highcharts Maps basic demo'
                },
                mapNavigation: {
                    enabled: true,
                    buttonOptions: {
                        verticalAlign: 'bottom'
                    }
                },
                colorAxis: {
                    min: 0
                },
                series: [{
                    data: data.map(function(item) {
                        return {
                            'hc-key': item[0],
                            value: item[1],
                            name: item[2]
                        };
                    }),
                    name: 'Sales Data',
                    states: {
                        hover: {
                            color: '#BADA55'
                        }
                    },
                    dataLabels: {
                        enabled: true,
                        format: '{point.name}: $ {point.value}'
                    }
                }]
            });
        })();
    }
});

</script>


{%  endblock %}

scr/templates/index.html
{% extends './base.html' %}

{% block title %}Index {% endblock %}

{% block body %}

{% endblock %}